server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    types {
        text/javascript jsx js;
        text/html html htm;
    }

    location = / {
        default_type text/html;
        try_files /index-dark.html =404;
    }

    location = /library {
        default_type text/html;
        try_files /library.html =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
